blank_issues_enabled: false
contact_links:
  - name: GitHub
    url: https://github.com/VincentX0905
    about: My Guthub | 我的Github
  - name: Discord
    url: https://discord.fsbot.xyz/
    about: Discord Guild | Discord群組
